<?php
/*
 * This file belongs to the YIT Framework.
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE (GPL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 */

return array(

    'border-1-top'    => '.blog.small .yit_post_meta,
                          .blog.masonry .yit_post_meta,
                          .yit_shortcodes.recent-post .blog.small .yit_post_meta,
                          .single-product.woocommerce div.product div.product-title-section,
                          #payment,
                          #my-account-content .digital-downloads,
                          #my-account-content .myaccount_address,
                          #inquiry-form,
                          #bbpress-forums div.bbp-reply-author .bbp-reply-ip,
                          #bbpress-forums div.bbp-reply-header',

    'border-1-bottom' => '.blog.big.single .yit_post_content.title,
                          #header-container .header-wrapper,
                          .woocommerce ul.product_list_widget li,
                          .widget.yit_products_category ul.product_list_widget li,
                          .widget.contact-info ul li,
                          #comments .comments-title:after,
                          #respond .comment-reply-title:after,
                          #reply-title:after,
                          #page-meta,
                          #portfolio_nav,
                          .widget.contact-info ul li,
                          #wp-calendar caption,
                          .woocommerce .cart-collaterals .cart_totals h3,
                          #order_review_heading, #payment h3,
                          .woocommerce table.shop_table.cart tbody,
                          #yith-wcwl-form table.shop_table tbody,
                          .woocommerce .cart-collaterals .cart_totals tbody tr.shipping,
                          #payment li,
                          .widget_categories  ul  li,
                          .widget_archive  ul  li,
                          .widget_product_categories ul li
                          .widget_meta  ul  li,
                          .widget_pages ul  li,
                          .widget_nav_menu  ul  li,
                          #order_review table tbody,
                          .contact-info ul li,
                          #order_review table tfoot tr.shipping,
                          .widget.widget_recent_entries ul li,
                          .widget.widget_recent_comments ul li,
                          .widget.yit_toggle_menu ul.menu > li,
                          .widget_product_categories ul.product-categories > li,
                          .widget.woocommerce.widget_layered_nav ul.yith-wcan-list li,
                          .woocommerce.widget_layered_nav ul li,
                          #header .widget_shopping_cart .widget_shopping_cart_content h5.list-title,
                          #inquiry-form,
                          .widget_product_categories ul li:not(.cat-parent),
                          .widget_product_categories ul li:not(.opened),
                          .widget_meta ul li,
                          #header .widget_shopping_cart .widget_shopping_cart_content ul.product_list_widget li,
                          .yit-vertical-megamenu .nav > ul > li,
                          .woocommerce .coupon-form-checkout,
                          .woocommerce .login-form-checkout,
                          #bbpress-forums #bbp-single-user-details #bbp-user-navigation li,
                          .yit_post_quote,
                          .st-menu ul li',

    'border-1-all'    => '.header-nav > ul > li > a,
                          .blog .yit_post_meta_date,
                          .blog.big .thumbnail,
                          .teaser-wrapper,
                          .blog-section-wrapper .yit_post_content,
                          .call-to-action-two,
                          .call-three,
                          .logos-slider.wrapper .nav .prev, .logos-slider.wrapper .nav .next,
                          .newsletter_form_email input.email-field,
                          .eg-item-skin-1-wrapper.filter-hover1 .esg-bc.eec,
                          .blog.big .yit_post_content,
                          .post.no-featured:not(.format-quote) .blog.big .yit_post_content,
                          .post.format-quote .blog.big .yit_post_content,
                          .format-quote .blog.big .yit_the_content:after,
                          .blog.small .post-wrapper,
                          .blog.masonry .post-wrapper,
                          .blog.big.single .yit_post_meta.last_block,
                          .toggle,
                          .price-table,
                          .tabs-container ul.tabs li,
                          .tabs-container ul.tabs,
                          #footer .border,
                          #copyright .border,
                          .widget_search #s,
                          .newsletter_form_email input,
                          .features-tab-container ul.features-tab-labels,
                          .features-tab-container ul.features-tab-labels li,
                          .blog-section-wrapper ul.blog_posts li div.blog_post .yit_post_date,
                          .testimonial-wrapper,
                          .toggle .toggle-title span.fa.fa-plus.closed,
                          .toggle .toggle-title span.fa.fa-minus.opened,
                          .arrow:before, .arrow-down:before,
                          #comments ol li .content,
                          #comments ol li .avatar img,
                          #commentform .comment-form-comment #comment,
                          #commentform input:not([type=submit]),
                          #commentform .comment-form-comment #comment,
                          .contact-form li div.input-prepend input[type=text],
                          .contact-form li.textarea-field div.input-prepend textarea,
                          #faqs-container .faq-wrapper,
                          .filters li a,
                          #buddypress form#whats-new-form textarea,
                          #buddypress div.item-list-tabs ul li.selected a,
                          #buddypress div.item-list-tabs ul li a,
                          #buddypress div.item-list-tabs ul li span,
                          #buddypress div.item-list-tabs ul:after,
                          #buddypress div.item-list-tabs ul li.current a,
                          #buddypress div.item-list-tabs#subnav > ul,
                          #buddypress ul li .item-container,
                          #buddypress div.dir-search label input[type="text"],
                          #faqs-container .faq-icon.fa,
                          .widget.yit-recent-posts .recent-post .hentry-post .text p:before,
                          #reviews #comments div.comment-text,
                          #reviews #comments ol.commentlist img.avatar,
                          .single-product.woocommerce div.woocommerce-tabs ul.tabs,
                          #reviews #comments div.comment-text.arrow-left:after,
                          #reviews #comments div.comment-text.arrow-left:before,
                          #reviews #comments > h3:after, #comments time:after,
                          #product-nav > a div.product-info,
                          .woocommerce ul.products li.product.grid .product-wrapper.elegant:hover .product-meta-wrapper,
                          #portfolio_small li .info,
                          #portfolio_content .portfolio_meta:after,
                          #portfolio_content .the_content.with-border:after,
                          #portfolio_content .testimonial-box.with-border:after,
                          .widget.yit_quick_contact ul li input:not([type="submit"]),
                          .widget.yit_quick_contact ul li textarea,
                          .woocommerce ul.products li.product.list .product-meta-wrapper div.product-rating:after,                          
                          .widget.yit-recent-comments div.comment,
                          .widget.yit-recent-comments .the-post .gravatar-wrapper,
                          .widget.yit_recent_reviews .review-content,
                          .widget.yit_recent_reviews .review-meta-avatar .avatar-thumb,
                          div.widget.teaser .teaser-wrapper,
                          input[type="text"],
                          input[type="password"],
                          input[type="email"],
                          input[type="tel"],
                          input.input-text,
                          input.input-text,
                          .woocommerce-page .woocommerce-page input.input-text,
                          textarea,
                          .cta-phone,
                           .yit-vertical-megamenu,
                           .yit-vertical-megamenu h3:after,
                          #review-order-wrapper,
                          .woocommerce .cart-collaterals,
                          .woocommerce table.shop_table.cart thead,
                          #yith-wcwl-form table.shop_table thead,
                          .woocommerce form .form-row a.chosen-single,
                          .woocommerce form .form-row textarea,
                          .woocommerce .quantity input.qty,
                          .woocommerce-page .quantity input.qty,
                          .woocommerce .quantity .minus,
                          .woocommerce .quantity .plus,
                          .woocommerce-page .quantity .minus,
                          .woocommerce-page .quantity .plus,
                          .sbHolder .sbSelector,
                          .sbHolder .sbOptions,
                          .widget.newsletter-form.with-border,
                          .widget_shopping_cart .widget_shopping_cart_content,
                          .woocommerce form .form-row div.chosen-drop,
                          .widget.last-tweets .arrow-left,
                          .arrow-left:before,
                          .arrow-left:after,
                          .border-line,
                          .team-section .member,
                          .team-section .member:after,
                          .team-section .member-info .member-name:after,
                          #portfolio_nav > a .info,
                          #my-account-sidebar ul li,
                          #my-account-sidebar ul:after,
                          .yit_shortcodes.recent-post .blog.small .post-wrapper,
                          .yit_shortcodes.recent-post .blog .yit_post_meta_date,
                          .yit_shortcodes.recent-post .blog .more-link,
                          .woocommerce-page table.shop_table.my_account_orders thead,
                          .widget.yith-woo-ajax-navigation ul.yith-wcan-color li a, 
                          .widget.yith-woo-ajax-navigation ul.yith-wcan-label li a,
                          .sidebar .widget.yit_text_image .clearfix.widget-wrap,
                          .woocommerce ul.order_details li, .woocommerce-page ul.order_details li,
                          .woocommerce table.shop_table.order_details thead,
                          .woocommerce table.shop_table.order_details tbody,
                          .woocommerce-page table.shop_table.my_account_orders thead,
                          .woocommerce table.shop_table.order_details tfoot tr:last-child,
                          .woocommerce-page table.shop_table.my_account_orders thead,
                          .widget.testimonial-widget ul li div.testimonial-description,
                          .widget.featured-products .flex-viewport,
                          .widget.testimonial-widget ul li .image-container,
                          #my-account-content h2:after,
                          .widget.yit_recent_reviews .owl-controls .owl-buttons span.fa,
                          #primary .testimonial-widget .owl-buttons .owl-next,
                          #primary .testimonial-widget .owl-buttons .owl-prev,
                          #welcome-menu-login .login-box.with_registration .customer-login-box.customer-login-box1,
                          #welcome-menu-login .login-box.with_registration .customer-login-box.customer-login-box2,
                          .woocommerce.widget.yith_woocommerce_ajax_search input[type="search"],
                          #bbpress-forums #bbp-single-user-details,
                          #bbpress-forums #bbp-single-user-details #bbp-user-avatar img.avatar,
                          #bbpress-forums li.bbp-header,
                          #bbpress-forums li.bbp-body,
                          .woocommerce.widget.widget_product_search #searchform,
                          #modal-window,
                          #bbpress-forums input[type="text"],
                          .bbp_widget_login input[type="text"],
                          .bbp_widget_login input[type="password"],
                          #bbpress-forums div.bbp-the-content-wrapper,
                          #bbpress-forums li.bbp-body div.bbp-reply-content,
                          #bbpress-forums li.bbp-body div.bbp-topic-content,
                          #bbpress-forums li.bbp-body div.bbp-reply-content:before,
                          #bbpress-forums li.bbp-body div.bbp-topic-content:before,
                          #bp-login-widget-form input[type="text"],
                          #bp-login-widget-form input[type="password"],
                          .woocommerce-billing-fields select,
                          .page-template-blog-php .post.blog-big,
                          .woocommerce-checkout .select2-container .select2-choice,.woocommerce-checkout .select2-drop-active,
                          .woocommerce-cart #calc_shipping_country,.woocommerce-cart #calc_shipping_state,.select2-drop.select2-drop-above.select2-drop-active,
                          .select2-dropdown-open.select2-drop-above .select2-choice, .select2-dropdown-open.select2-drop-above .select2-choices,
                          .select2-drop.select2-drop-above.select2-drop-active',

    'border-2-bottom' => '',

    'border-2-top'    => '',

    'border-2-all'    => '.dropcap,
                          .images-slider-sc .flex-direction-nav li a:hover,
                          #nav .menu-item .highlight,
                          #comments ol li .information .user-info .is_author,
                          #commentform input:not([type=submit]):focus,
                          #commentform .comment-form-comment #comment:focus,
                          .contact-form li div.input-prepend input[type=text]:focus,
                          .contact-form li.textarea-field div.input-prepend textarea:focus,
                          .filters li a.active,
                          .filters li a:hover,
                          .widget.featured-products .flex-direction-nav li a.flex-next:hover,
                          .widget.featured-products .flex-direction-nav li a.flex-prev:hover',

    'border-3-bottom' => '.features-tab-container ul.features-tab-labels li.current-feature,
                          .blog.big:not(.single) .yit_post_meta:after',

    'border-3-top'    => '.yit_post_quote',

    'border-3-all'    => '.blog.big .yit_post_meta:after, .images-slider-sc .flex-direction-nav li a,
                          .logos-slider .nav .prev, .logos-slider .nav .next,
                          .woocommerce ul.products li.product .thumb-wrapper.alternative .product-action-button a,
                          .widget.yit-recent-posts .recent-post .hentry-post p.post-date,
                          .single-product.woocommerce div.product div.summary .price:after,
                          .single-product.woocommerce div.product div.summary .product_meta:before,
                          .woocommerce ul.products li.product .product-wrapper.elegant:hover .product-meta-wrapper:before,
                          .woocommerce ul.products li.product .product-wrapper.elegant:hover .product-meta-wrapper:after,
                          .single-product.woocommerce div.product div.summary ul.socials li,
                          .woocommerce ul.products li.product .thumb-wrapper .out-of-stock-icon .out-of-stock-text:before,
                          .woocommerce ul.products li.product .thumb-wrapper .out-of-stock-icon .out-of-stock-text:after,
                          .widget_categories .sbHolder .sbSelector,
                          .woocommerce ul.products li.product .thumb-wrapper .added-to-cart-icon .added-to-cart-text:before,
                          .woocommerce ul.products li.product .thumb-wrapper .added-to-cart-icon .added-to-cart-text:after,
                          .widget_archive .sbHolder .sbSelector,
                          .woocommerce .cart-empty h2.empty-message:after,
                          .widget.featured-products div.info-featured-product > div,
                          .widget.featured-products .flex-direction-nav li a.flex-next,
                          .widget.featured-products .flex-direction-nav li a.flex-prev,
                          #show-category-product div.category-count div.category-count-content span,
                          #show-category-product div.category-name h4, .categories-slider div.category-name h4,
                          .woocommerce-message,
                          .woocommerce-info,
                          #header-search input#s, #header-search input#yith-s',


    'border-4-bottom' => '',

    'border-4-top'    => '',

    'border-4-all'    => '',

    'a-tag-style-1'           => 'a, a:visited,
                                  .widget.yit-recent-posts .recent-post .hentry-post h3 a.title:hover,
                                  .widget.woocommerce ul.product_list_widget a span.product_title:hover,
                                  .widget.contact-info .info-container a.contact_info_email:hover h4,
                                  .contact-info .info-container a:hover h4,
                                  .blog-section-wrapper ul.blog_posts li div.blog_post .yit_post_meta span.title a:hover,
                                  .blog-section-wrapper ul.blog_posts li div.blog_post .yit_post_meta span.info a:hover,
                                  .widget.yit-recent-comments .comments-info-wrapper a.title:hover,
                                  .widget.yit_recent_reviews .review-meta-avatar .meta .product-review-link a:hover,
                                  .product-meta h3.product-name a:hover,
                                  .woocommerce table.cart td.product-name div.product-name a:hover,
                                  .sbHolder .sbOptions li a:hover,
                                  .widget_shopping_cart .widget_shopping_cart_content .mini-cart-item-info a:hover,
                                  .widget_nav_menu ul li a:hover,
                                  .widget_product_categories ul li a:hover,
                                  .wishlist_table tr td.product-name a:hover,
                                  li.eg-item-skin-1-wrapper.filter-hover1:hover .esg-bc.eec .eg-item-skin-1-element-16,
                                  .widget.woocommerce.widget_layered_nav ul.yith-wcan-list li a:hover,
                                  .woocommerce.widget_layered_nav ul li a:hover,
                                  .widget.featured-products div.info-featured-product a:hover,
                                  .widget.yit_products_category a span.product_title:hover,
                                  #wp-calendar tbody tr td#today,
                                  #buddypress #activity-stream li .activity-meta a.fav:hover,
                                  #header #welcome-menu-login .lost_password a:hover,
                                  #customer_login .login .lost_password a:hover,
                                  #bbpress-forums li.bbp-forum-info a:hover,
                                  #bbpress-forums li.bbp-topic-title a.bbp-topic-permalink:hover,
                                  #bbpress-forums div.bbp-reply-author a.bbp-author-name:hover,
                                 .widget.widget_display_views ul li a.bbp-view-title:hover,
                                 .widget.widget_display_topics ul li a.bbp-forum-title:hover,
                                 .widget.widget_display_forums ul li a.bbp-forum-title:hover,
                                 .widget.buddypress .bp-login-widget-user-links > div.bp-login-widget-user-link a:hover,
                                 .buddypress.widget ul li.vcard a:hover,
                                 .sitemap a:hover,
                                  #yit-breadcrumb a:hover,
                                 .widget.yit-recent-posts .recent-post.compact .hentry-post h3 a.title:hover,
                                 .widget.yit-recent-posts .recent-post.compact span.author a:hover,
                                 .widget.yit-recent-posts .recent-post.compact span.num-comments a:hover,
                                 .widget.yit-recent-comments .comments-info-wrapper .author .email:hover',

    'a-tag-style-1-hover'     => 'a:hover, a:active, .widget.woocommerce ul.product_list_widget a span.product_title,
                                  .widget.yit-recent-comments .comments-info-wrapper a.title,
                                  .contact-info .info-container h4,
                                  .contact-info .info-container a h4,
                                  .widget.yit_recent_reviews .review-meta-avatar .meta .product-review-link a,
                                  #number-of-products a:hover,
                                  #number-of-products a.active,
                                  #yit-breadcrumb a,
                                  .blog-section-wrapper ul.blog_posts li div.blog_post .yit_post_meta span.title a,
                                  .widget_nav_menu ul li a,
                                  .widget_product_categories ul li a,
                                  .widget.woocommerce.widget_layered_nav ul.yith-wcan-list li a,
                                  .woocommerce.widget_layered_nav ul li a,
                                  .widget.featured-products div.info-featured-product a,
                                  .widget.yit_products_category a span.product_title,
                                  li.eg-item-skin-1-wrapper.filter-hover1 .esg-bc.eec .eg-item-skin-1-element-16,
                                  #buddypress #activity-stream li .activity-meta a.fav,
                                  #header #welcome-menu-login .lost_password a,
                                  #customer_login .login .lost_password a,
                                  #bbpress-forums div.bbp-reply-author a.bbp-author-name,
                                  .widget.buddypress .bp-login-widget-user-links > div.bp-login-widget-user-link a,
                                  .buddypress.widget ul li.vcard a',

    'a-tag-style-2'           => '.features-tab-container ul.features-tab-labels li h4 a,
                                  .tabs-container ul.tabs li h4 a,
                                  .woocommerce-product-rating .woocommerce-review-link,
                                  .single-product.woocommerce div.product div.summary ul.socials li a,
                                  .single-product.woocommerce div.product div.summary .product-actions-wrapper .yith-wcwl-add-to-wishlist a,
                                  ul.products li.product.list .product-wrapper .product-actions-wrapper .yith-wcwl-add-to-wishlist a,
                                  .widget_categories  ul  li a,
                                  .widget_archive  ul  li a,
                                  .widget_product_categories ul li a,
                                  .widget_meta  ul  li a,
                                  .widget_pages ul  li a,
                                  .widget_nav_menu  ul  li a,
                                  .logos-slider.wrapper .nav a.next,
                                  .logos-slider.wrapper .nav a.prev,
                                  .logos-slider.wrapper .nav a.next:hover,
                                  .logos-slider.wrapper .nav a.prev:hover,
                                  .blog-section-wrapper ul.blog_posts li div.blog_post .yit_post_meta span.info a,
                                  #yith-wcwl-form .yith-wcwl-share ul li a,
                                  .single-product.woocommerce div.product div.summary form.cart ul.variations .select_option,
                                  .single-product.woocommerce form.cart .reset_variations,
                                  .single-product.woocommerce div.product div.summary form.cart ul.variations .select_option span,
                                  #modal-window div.modal-opener a,
                                  .widget.featured-products .flex-direction-nav li a.flex-prev:before,
                                  .widget.featured-products .flex-direction-nav li a.flex-next:before,
                                  .woocommerce .products-slider-wrapper .es-nav-prev span,
                                  .woocommerce .products-slider-wrapper .es-nav-next span,
                                  .categories-slider-wrapper .es-nav-prev span,
                                  .categories-slider-wrapper .es-nav-next span,
                                  .coupon-form-checkout a.showcoupon,
                                  .login-form-checkout a.showlogin,
                                  .login-form-checkout .lost_password a,
                                  .widget.yit_toggle_menu ul.menu li a,
                                  #buddypress div.item-list-tabs ul li a,
                                  #buddypress #activity-stream p a:hover,
                                  .yit-vertical-megamenu .nav > ul > li > a,
                                  .quick-view-overlay.product-quick-view a.overlay-close.remove,
                                  .yitpopup_wrapper a.close:before,
                                  .quick-view-overlay.product-quick-view .slider-quick-view-container .es-nav-prev,
                                  .quick-view-overlay.product-quick-view .slider-quick-view-container .es-nav-next,
                                  #header-search .autocomplete-suggestion,
                                  #inquiry-form .product-inquiry,
                                  .widget.widget_display_topics a.bbp-author-name,
                                  .widget.widget_display_replies a.bbp-author-name,
                                  .buddypress.widget #members-list-options a,
                                  .sitemap a,
                                  .woocommerce .widget_layered_nav ul.yith-wcan-label li a,
                                  .woocommerce-page .widget_layered_nav ul.yith-wcan-label li a',

    'a-tag-style-2-hover'     => '.features-tab-container ul.features-tab-labels li.current-feature h4 a,
                        .features-tab-container ul.features-tab-labels li.current-feature:hover h4 a,
                        .features-tab-container ul.features-tab-labels li:hover h4 a,
                        .features-tab-container ul.features-tab-labels li h4 a:hover,
                        .woocommerce-product-rating .woocommerce-review-link:hover,
                        .toggle .toggle-title h4:hover,
                        .toggle .toggle-title.tab-opened h4,
                        .toggle .toggle-title:hover span.fa.fa-plus.closed,
                        .toggle .toggle-title span.fa.fa-plus.closed:hover,
                        .toggle .toggle-title span.fa.fa-minus.opened:before,
                        #faqs-container .faq-wrapper:hover .faq-title h4,
                        #faqs-container .faq-wrapper .faq-title.active h4,
                        #faqs-container .faq-wrapper:hover .faq-icon.fa,
                        #faqs-container .faq-wrapper .faq-title.active .faq-icon.fa,
                        .widget_categories  ul  li a:hover,
                        .widget_archive  ul  li a:hover,
                        .widget_product_categories ul li a:hover,
                        .widget_meta  ul  li a:hover,
                        .widget_pages ul  li a:hover,
                        .widget_nav_menu  ul  li a:hover,
                        .filters li a:hover,
                        .filters li a.active,
                        .single-product.woocommerce div.woocommerce-tabs ul.tabs li a:hover,
                        .single-product.woocommerce div.woocommerce-tabs ul.tabs li.active a,
                        .tabs-container ul.tabs li h4 a:hover,
                        div.product div.summary .product_meta span a:hover,
                        .single-product.woocommerce div.product div.summary ul.socials li a:hover i.fa,
                        .single-product.woocommerce div.product div.summary .product-actions-wrapper .yith-wcwl-add-to-wishlist a:hover,
                        ul.products li.product.list .product-wrapper .product-actions-wrapper .yith-wcwl-add-to-wishlist a:hover,
                        #product-nav > a:hover span,
                        .single-product.woocommerce div.product div.summary ul.socials li a:hover,
                        #yith-wcwl-form .yith-wcwl-share ul li a:hover,
                        #my-account-sidebar ul li > a:hover,
                        #my-account-sidebar ul li > a.active,
                        #buddypress div.item-list-tabs ul li a:hover,
                        #buddypress #activity-stream p a,
                        .single-product.woocommerce div.product div.summary form.cart ul.variations .select_option:hover,
                        .single-product.woocommerce div.product div.summary form.cart ul.variations .select_option.selected,
                        .single-product.woocommerce form.cart .reset_variations:hover,
                        .single-product.woocommerce div.product div.summary form.cart ul.variations .select_option span:hover,
                        .single-product.woocommerce div.product div.summary form.cart ul.variations .select_option.selected span,
                        #modal-window div.modal-opener a:hover,
                        .widget.featured-products .flex-direction-nav li a.flex-prev:hover:before,
                        .widget.featured-products .flex-direction-nav li a.flex-next:hover:before,
                        .woocommerce .products-slider-wrapper .es-nav-prev:hover span,
                        .woocommerce .products-slider-wrapper .es-nav-next:hover span,
                        .categories-slider-wrapper .es-nav-prev:hover span,
                        .categories-slider-wrapper .es-nav-next:hover span,
                        .coupon-form-checkout a.showcoupon:hover,
                        .login-form-checkout a.showlogin:hover,
                        .login-form-checkout .lost_password a:hover,
                        .widget.yit_toggle_menu ul.menu li a:hover,
                        .quick-view-overlay.product-quick-view a.overlay-close.remove:hover,
                        .quick-view-overlay.product-quick-view .slider-quick-view-container .es-nav-prev:hover,
                        .quick-view-overlay.product-quick-view .slider-quick-view-container .es-nav-next:hover,
                        .yitpopup_wrapper a.close:hover:before,
                        #header-search .autocomplete-suggestion:hover,
                        #header #header-search.opened .widget_search a.trigger-search, #header #header-search.opened .widget_product_search a.trigger-search,
                        #inquiry-form .product-inquiry:hover,
                        #bbpress-forums li.bbp-forum-info a,
                        #bbpress-forums li.bbp-topic-title a.bbp-topic-permalink,
                        #bbpress-forums li a:hover,
                        .widget.widget_display_topics a.bbp-author-name:hover,
                        .widget.widget_display_replies a.bbp-author-name:hover,
                        .buddypress.widget #members-list-options a:hover,
                        .buddypress.widget #members-list-options a.selected,
                        .sitemap h4 a,
                        .woocommerce .widget_layered_nav ul.yith-wcan-label li a:hover,
                        .woocommerce-page .widget_layered_nav ul.yith-wcan-label li a:hover,
                        .woocommerce .widget_layered_nav ul.yith-wcan-label li.chosen a,
                        .woocommerce-page .widget_layered_nav ul.yith-wcan-label li.chosen a',

    'p-tag'           => 'p, body, time, dt, dd, td, th, address, .counter .text, ul.short li, .testimonial-wrapper .testimonial-smallquote,
                          .widget.yit-recent-posts .recent-post .hentry-post p.post-date .month,
                          div.product div.summary .product_meta span a,
                          .woocommerce p.form-row label, #ship-to-different-address label,
                          .woocommerce .quantity input.qty,
                          .woocommerce-page .quantity input.qty,
                          .woocommerce .quantity .minus,
                          .woocommerce .quantity .plus,
                          .woocommerce-page .quantity .minus,
                          .woocommerce-page .quantity .plus,
                          .sbHolder .sbSelector,
                          .blog-section-wrapper ul.blog_posts li div.blog_post .yit_post_date .month,
                          .sbHolder .sbOptions li a,
                          .woocommerce .form-row .chosen-container-single .chosen-single,
                          #customer_login p label,
                          #my-account-content p label,
                          #my-account-content #wp-social-login-connect-with,
                          #bbpress-forums #bbp-your-profile fieldset label[for],
                          #bbpress-forums fieldset label[for],
                          .bbp_widget_login label[for],
                          #bbpress-forums li a,
                          #bbpress-forums li.bbp-header li,.select2-container .select2-choice',
);